formatted docker build command

diff --git a/.github/workflows/solar-system-1.yml b/.github/workflows/solar-system-1.yml
--- a/.github/workflows/solar-system-1.yml
+++ b/.github/workflows/solar-system-1.yml
@@ -31,22 +31,24 @@ jobs:
           run: |
             docker run -it -d --name my-running-app -p 3000:3000 solar-system:${{ github.sha }}
             docker ps -a
-            # Wait up to 30 seconds for the service to be ready
-            for i in {1..15}; do
-              if curl -s http://localhost:3000/ > /dev/null; then
-                echo "Frontend is ready!"
-                break
-              fi
-              echo "Waiting for frontend to be ready... ($i)"
-              sleep 2
-            done
+            sleep 10
+            (curl http://localhost:3000/ready | grep "ready") || (docker logs my-running-app && exit 1)
+            # # Wait up to 30 seconds for the service to be ready
+            # for i in {1..15}; do
+            #   if curl -s http://localhost:3000/ > /dev/null; then
+            #     echo "Frontend is ready!"
+            #     break
+            #   fi
+            #   echo "Waiting for frontend to be ready... ($i)"
+            #   sleep 2
+            # done
 
-            # Final check (with failure if not ready)
-            curl -sSf http://localhost:3000/ | grep "<html>" || {
-              echo "Frontend not responding correctly"
-              docker logs my-running-app
-              exit 1
-            }
+            # # Final check (with failure if not ready)
+            # curl -sSf http://localhost:3000/ | grep "<html>" || {
+            #   echo "Frontend not responding correctly"
+            #   docker logs my-running-app
+            #   exit 1
+            # }
             
 
             
